import type { Metadata } from "next";
import { Noto_Sans, Noto_Sans_Mono } from "next/font/google";
import "./globals.css";

const fontSans = Noto_Sans({
	variable: "--font-sans",
	subsets: ["latin"],
});

const fontMono = Noto_Sans_Mono({
	variable: "--font-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={`${fontSans.variable} ${fontMono.variable} antialiased`}
		>
			<body className="flex h-dvh min-h-full flex-col items-center justify-center bg-linear-to-b from-gray-50 to-[#d2d6db] bg-no-repeat">
				{children}
			</body>
		</html>
	);
}
